GET http://localhost:5000/users
Content-Type: application/json

###

POST http://localhost:5000/auth/register
Content-Type: application/json 

{
    "name": "mjau",
    "password": "mjau"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "name": "mjau",
    "password": "mjau"
}